name: Pure TWRP Recovery Builder

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Clean Environment
      run: |
        sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php
        sudo apt-get clean
        
    - name: Install Build Dependencies & Repo Tool
      run: |
        sudo apt-get update
        sudo apt-get install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev python3 repo

    - name: Initialize Pure TWRP Source Sync
      run: |
        mkdir ~/twrp && cd ~/twrp
        git config --global user.name "Builder"
        git config --global user.email "builder@email.com"
        
        # INAYOS: Pinalitan ng Opisyal na Minimal TWRP Manifest para sa Android 12.1/14 compilation
        repo init --depth=1 -u https://github.com -b twrp-12.1 --no-clone-bundle
        repo sync -c -j$(nproc) --force-sync --no-clone-bundle --no-tags || repo sync -c -j2 --force-sync --no-clone-bundle --no-tags

    - name: Clone Your Device Tree
      run: |
        mkdir -p ~/twrp/device/tecno/TECNO-CK7n
        git clone https://github.com -b fox_12.1 ~/twrp/device/tecno/TECNO-CK7n

    - name: Start Building TWRP Recovery Image
      run: |
        cd ~/twrp
        . build/envsetup.sh
        export ALLOW_MISSING_DEPENDENCIES=true
        lunch twrp_TECNO-CK7n-eng || lunch omni_TECNO-CK7n-eng
        mka recoveryimage -j$(nproc)

    - name: Upload Finished TWRP File
      uses: actions/upload-artifact@v4
      with:
        name: Pure_TWRP_Recovery_Tecno_Camon_20_Pro
        path: ~/twrp/out/target/product/TECNO-CK7n/recovery.img
